    
name: CPASS-Toolkit
description: This is the CPASS-toolkit theme built using the Radius template language for CleanSlate. Originally authored by Cole Smith.

# CSS
css: 
  
  # Turn CSS compression/minification on/off.
  compress: true
  
# JavaScript options
js:
  
  # Turn JavaScript compression/minification on/off
  compress: true
  
  # Turn JavaScript mangling on/off.
  mangle: true